artifact_root: artifact

data_ingestion:
  root_dir: artifact/data_ingestion
  data_path: "https://drive.google.com/uc?export=download&id=1OPoYRR_GjdedXQrBiRzV0wPQaNCPmm0I"
  zip_file: artifact/data_ingestion/data.zip
  unzip_file: artifact/data_ingestion

data_validation:
  root_dir: artifact/data_validation
  data_path: artifact/data_ingestion/combined_data.csv
  status_file: artifact/data_validation/status.txt

data_transformation:
  root_dir: artifact/data_transformation
  data_path: artifact/data_ingestion/combined_data.csv

model_building:
  root_dir: artifact/build_model
  xtrain_data: artifact/data_transformation/x_train.pkl
  ytrain_data: artifact/data_transformation/y_train.pkl
  model: model.pkl

model_evaluation:
  root_dir: artifact/model_evaluation
  xval_data: artifact/data_transformation/x_val.pkl
  yval_data: artifact/data_transformation/y_val.pkl
  model: artifact/build_model/model.pkl
  metric_file: artifact/model_evaluation/mertic.json
